### ISSUE TITLE
Emojiful breaks Patchouli book fonts and formatting

### ISSUE THREAD

**Issue by dandin87** [InnovativeOnlineIndustries/Emojiful#78]
Emojiful breaks Patchouli book fonts and formatting. With the first example it only looks correct at one of the gui scales.
Examples
Modern Industrialization
![image](https://user-images.githubusercontent.com/9329117/232887836-418d6e3d-78a0-417d-b4de-4abbb834ad89.png)

Fabric Seasons
![image](https://user-images.githubusercontent.com/9329117/232888513-86f9b68a-9ff9-4f2f-b8b0-033e0e074506.png)

**Comment by Lgmrszd** [comment]
Could https://github.com/VazkiiMods/Patchouli/issues/306 (as well as #8) be relevant? Seems was fixed back in 1.16 but reappeared now.

**Comment by Buuz135** [comment]
I dont think I can do much about it :(

**Comment by Buuz135** [comment]
Could you check if it happens with version v1.19.2-4.0.5

**Comment by IdrisQe** [comment]
Hi! I know this is an old issue but I'm playing a modpack using 4.0.5, and I'm afraid it didn't fix the problem. The issue still occurs: https://github.com/katubug/CottageWitch119/issues/69
